#!/bin/dash

export ROBO_BASE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export PATH="$ROBO_BASE/bin:$PATH"
. "$ROBO_BASE/config"
if [ -e "$ZADAN_BASE/userconfig" ]; then
	. "$ROBO_BASE/userconfig"
fi
export debian_chroot="ROBO"
exec "$SHELL" "$@"
